all_data_years: [2016, 2017, 2018, 2019, 2020, 2021, 2022]
model_years: [2016, 2017, 2018, 2019]
prev_data_only: FALSE
out_of_sample: FALSE
duration:
  intercept: 1.51
  slope: 0.42
covs:
  prev: [
    'intercept', 'hh_crowding_norm', 'log_ntl_norm', 'hiv_norm', 'refugees_pct_norm',
    'cattle_pc_norm'
  ]
  comp: ['intercept', 'tt_hcf_norm']
shapefile_settings:
  modeling_level: 2
  ids:
    adm1: ['ADM1_EN']
    adm2: ['ADM1_EN','ADM2_EN','uid']
covariate_settings:
  file_format: 'tif'
  add_intercept: FALSE
  trim_comp_covariates: TRUE
pop_covariate_settings:
  covariate: 'worldpop_total'
  annual: TRUE
  transform: 'identity'
  normalize: FALSE
priors:
  prior_beta_covs:
    name: 'gaussian'
    par1: 0
    par2: 3
  prior_beta_comp_t:
    name: 'gaussian'
    par1: 0
    par2: 3
  prior_rho_Z_prev:
    name: 'beta'
    par1: 2.5
    par2: 1.5
  prior_rho_Z1_comp:
    name: 'beta'
    par1: 2.5
    par2: 1.5
  prior_rho_Z2_comp:
    name: 'beta'
    par1: 2.5
    par2: 1.5
  prior_sigma_Z_prev:
    name: 'gamma'
    par1: 1
    par2: 1
  prior_sigma_Z1_comp:
    name: 'gamma'
    par1: 1
    par2: 1
  prior_sigma_Z2_comp:
    name: 'gamma'
    par1: 1
    par2: 1
  prior_sigma_e_prev:
    name: 'gamma'
    par1: 1
    par2: .25
  prior_sigma_e_comp:
    name: 'gamma'
    par1: 1
    par2: .25
versions:
  results: '20231010_test'
directories:
  repo:
    versioned: FALSE
    path: '~/repos/uga_tb'
  shps:
    versioned: FALSE
    path: '~/temp_data/uga/raw_data/prepared_geometries'
    files:
      adm2: 'uga_ad2_analysis.shp'
      viz_adm0: 'uga_ad0_visualization.shp'
      viz_adm2: 'uga_ad2_visualization.shp'
  raw_data:
    versioned: FALSE
    path: '~/temp_data/uga/raw_data'
    files:
      refugees: 'covariate_prep/unhcr_refugees_pct_2022.csv'
      prev_survey: 'prev_survey/prev_survey_summary.csv'
      notifs_p1: 'dhis2_notifications/all_notifs_2016_2019_update.csv'
      ped_notifs_p1: 'dhis2_notifications/ped_notifs_2016_2019.csv'
      notifs_p2: 'dhis2_notifications/all_notifs_2020_2022.csv'
      ped_notifs_p2: 'dhis2_notifications/ped_notifs_2020_2022.csv'
      prop_over_15: 'gbd_2019_prop_over_15.csv'
      covariates_table: 'covariate_prep/covariates_table.csv'
  old_data:
    versioned: FALSE
    path: '~/temp_data/uga/prepped_data/20221009'
    files:
      shp: 'model_shp.shp'
      covs: 'dist_dt.csv'
  prepped_data:
    versioned: TRUE
    path: '~/temp_data/uga/prepped_data'
    files:
      model_shp: 'model_shp.shp'
      id_raster: 'id_raster.tif'
      link_table: 'link_table.csv'
      covariates: 'dist_dt.csv'
      prev_data: 'prev_data.csv'
      notif_data: 'notif_data.csv'
      adjmat: 'adjmat.RData'
  covariates:
    versioned: FALSE
    path: '~/temp_data/rr'
  model_results:
    versioned: TRUE
    path: '~/temp_data/uga/model_results'
    files:
      model_fit: 'model_fit.RDS'
      model_preds: 'model_preds.RDS'
      parameter_summary: 'parameter_summary.csv'
      prevalence_summary: 'prevalence_summary.csv'
      completeness_summary: 'completeness_summary.csv'
      incidence_summary: 'incidence_summary.csv'
      oos_summary: 'oos_summary.csv'
      completeness_observations: 'completeness_observations.csv'

